services:
  - type: web
    name: gnut-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python
    region: oregon
    plan: free
    autoDeploy: true
